assign buffer type so ts happy
ts failed to build because of:

```
src/components/image.tsx:27:19 - error TS2322: 
Type 'Uint8Array<ArrayBufferLike>' is not 
assignable to type 'BlobPart'.
  Type 'Uint8Array<ArrayBufferLike>' is not assignable to type 'ArrayBufferView<ArrayBuffer>'.
    Types of property 'buffer' are incompatible.
      Type 'ArrayBufferLike' is not assignable to type 'ArrayBuffer'.
        Type 'SharedArrayBuffer' is not assignable to type 'ArrayBuffer'.
          Types of property '[Symbol.toStringTag]' are incompatible.
            Type '"SharedArrayBuffer"' is not assignable to type '"ArrayBuffer"'.

27         new Blob([imageData], { type: "image/jpeg" }),
```

we use the buffer instead