set the UV_CACHE_DIR to /tmp to avoid cache problems on compute nodes
```sh
error: Could not acquire lock  Caused by: Could not acquire lock for
`~/.cache/uv` at `~/.cache/uv/.lock`  Caused by:
failed to lock `~/.cache/uv/.lock`: Unknown error
524 (os error 524)
```